<?php

namespace AppBundle\Repository;

/**
 * AnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswersRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllAnswersForQuestions($questionId) {

        return $this->createQueryBuilder('a')
            ->where('a.question_id = :questionId')
            ->setParametere(":questionId", $questionId)
            ->getSql()
            ->getArrayResult();
     }
}
