app_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }
admin_homepage:
    path: /admin
    defaults: { _controller: AppBundle:Admin:index }
admin_add_envelope:
    path: /admin/addEnvelope
    defaults: { _controller: AppBundle:Admin:addEnvelope }
admin_list_envelope:
    path: /admin/envelopeList
    defaults: { _controller: AppBundle:Admin:envelopeList}
admin_add_question:
    path: /admin/addQuestion
    defaults: { _controller: AppBundle:Admin:addQuestion}
admin_list_question:
    path: /admin/questionList
    defaults: { _controller: AppBundle:Admin:questionList}
admin_add_envelope:
    path: /admin/addAnswers
    defaults: { _controller: AppBundle:Admin:addAnswertoQuestion }
player_homepage:
    path: /player
    defaults: { _controller: AppBundle:Player:index }