AppBundle\Entity\Game:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        money:
            type: integer
    manyToOne:
        users:
          targetEntity: UserBundle\Entity\User
          joinColumn:
              name: user_id
              referencedColumnName: id
    manyToMany:
        game_questions:
            targetEntity: AppBundle\Entity\Questions
            joinTable:
                name: game_questions
                joinColumns:
                    game_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    question_id:
                        referencedColumnName: id
        game_envelopes:
            targetEntity: AppBundle\Entity\Envelopes
            joinTable:
                name: game_envelopes
                joinColumns:
                    game_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    envelope_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
