AppBundle\Entity\Questions:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\QuestionsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        question:
            type: text
    lifecycleCallbacks: {  }
